# Generated by Django 2.1.15 on 2021-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_setores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_nome', models.CharField(max_length=30)),
                ('resposavel_setor', models.CharField(max_length=30)),
                ('cargo_setor', models.CharField(max_length=30)),
                ('contato_setor', models.CharField(max_length=30)),
            ],
        ),
    ]
