# Generated by Django 2.1.15 on 2021-10-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cad_setores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_dpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cad_equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('responsabilidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cad_fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=30)),
                ('dpo', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
    ]
