# Generated by Django 2.1.15 on 2021-10-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cad_dpo_cad_equipes_cad_fornecedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_equipes',
            name='cargo',
        ),
    ]
