# Generated by Django 2.1.15 on 2021-11-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211031_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_fator_de_risco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_fator_de_risco', models.CharField(max_length=90)),
                ('fator_de_risco', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cad_dados_previos',
            old_name='questao',
            new_name='questao_dados_previos',
        ),
        migrations.RenameField(
            model_name='cad_itens_auditaveis',
            old_name='questao',
            new_name='questao_itens_auditaveis',
        ),
    ]
