# Generated by Django 2.1.15 on 2021-11-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211031_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_Mapeamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('fonte', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=30)),
                ('base_legal', models.CharField(max_length=30)),
                ('tratamento', models.CharField(max_length=30)),
                ('eliminacao', models.CharField(max_length=30)),
                ('compartilhamento', models.CharField(max_length=30)),
                ('necessario_consentimento', models.CharField(max_length=30)),
                ('possui_consentimento', models.CharField(max_length=30)),
                ('menor', models.CharField(max_length=30)),
                ('impacto_pessoal', models.CharField(max_length=30)),
                ('missao_critica', models.CharField(max_length=30)),
            ],
        ),
    ]
