# Generated by Django 2.1.15 on 2021-11-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cad_itens_auditaveis_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_itens_auditaveis',
            name='fr',
        ),
    ]
